spring.application.name=CodeCoach
ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent
spring.config.import=optional:file:.env[.properties]
ai.gemini.key=${GEMINI_API_KEY}
